Repository symbench/electric-circuits, pull requests merged in 2021-03, with the labels that each got.

#72 Refactor recommendation plugin to support multiple algs/models. Closes #71
  src/plugins/RecommendNextComponents/RecommendNextComponents.js
  src/plugins/RecommendNextComponents/RecommendNextComponents/__init__.py
  src/plugins/RecommendNextComponents/RecommendNextComponents/models/example/__init__.py
  src/plugins/RecommendNextComponents/metadata.json
  src/plugins/RecommendNextComponentsMock/RecommendNextComponentsMock/__init__.py
  src/plugins/RecommendNextComponentsMock/metadata.json
  test/plugins/RecommendNextComponents/RecommendNextComponents.spec.js
  webgme-setup.json
Labels: enhancement

#89 Sort recommendations by likelihood. Closes #88
  src/plugins/RecommendNextComponents/RecommendNextComponents/__init__.py
  src/plugins/RecommendNextComponents/RecommendNextComponents/models/example/__init__.py
  test/plugins/RecommendNextComponents/RecommendNextComponents.spec.js
Labels: enhancement, minor

#80 Add graph gym model to recommendation plugin. Closes #79
  src/plugins/RecommendNextComponents/RecommendNextComponents/models/graphconv/__init__.py
  src/plugins/RecommendNextComponents/RecommendNextComponents/models/graphconv/about.txt
  src/plugins/RecommendNextComponents/RecommendNextComponents/models/graphconv/config.yaml
  src/plugins/RecommendNextComponents/RecommendNextComponents/models/graphconv/mean.npy
  src/plugins/RecommendNextComponents/RecommendNextComponents/models/graphconv/model.ckpt
  src/plugins/RecommendNextComponents/RecommendNextComponents/models/graphconv/stddev.npy
  src/plugins/RecommendNextComponents/metadata.json
Labels: enhancement

#104 Use /tmp instead of ~. Closes #99
  utils/install-graphgym.sh
Labels: minor

#28 Test for node 12 and 14 in CI. Closes #27
  .github/workflows/test-deploy.yml
Labels: ci

#123 Edit graphgym config in memory. Closes #122
  src/plugins/RecommendNextComponents/RecommendNextComponents/models/graphconv/__init__.py
Labels: enhancement, minor
